
name: dev-yaml

spring:
  datasource:
    url: jdbc:postgresql://ec2-34-235-108-68.compute-1.amazonaws.com:5432/d5bfsrja8m10qf
    username: fqrbhhetzxifkk
    password: 4df081108851964a2eb51834da5089489d18e65f0608b4a1f9433d33170907a2
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true