
name: dev-yaml

spring:
  datasource:
    url: jdbc:postgresql://ec2-34-235-108-68.compute-1.amazonaws.com:5432/d5bfsrja8m10qf
    username: fqrbhhetzxifkk
    password: 4df081108851964a2eb51834da5089489d18e65f0608b4a1f9433d33170907a2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true


okta:  
  oauth2:  
    issuer: https://dev-137527.okta.com/oauth2/default
    client-id: 0oa2ibx8wdHZ7tg2n4x6
    scope: openid profile email


logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.security: DEBUG

