
name: dev-yaml

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-152-175-141.compute-1.amazonaws.com:5432/d5gj3ht8rar69a
    username: cksklnxxgmumpd
    password: 64f022fc4c60e36478fa5db8c6d3a194795e708c0ff2cc3a9f4462e7f3978487
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  mvc:
    dispatch-options-request: true
    


okta:  
  oauth2:  
    issuer: https://dev-137527.okta.com/oauth2/default
    client-id: 0oa2ibx8wdHZ7tg2n4x6
    scope: openid profile email


logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.security: DEBUG

